name: Android CI

env:
    # Gradle 빌드 성능 설정
    GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false"
    GRADLE_BUILD_ACTION_CACHE_DEBUG_ENABLED: true

on:
    pull_request:

jobs:
    ci-build:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout Code
                uses: actions/checkout@v4

            -   name: Setup JDK 21
                uses: actions/setup-java@v4
                with:
                    java-version: '21'
                    distribution: 'temurin'

            -   name: Setup Android SDK
                uses: android-actions/setup-android@v2

            -   name: Setup Gradle
                uses: gradle/gradle-build-action@v2
                with:
                    gradle-home-cache-cleanup: true

            -   name: Grant execute permission for gradlew
                run: chmod +x gradlew

            -   name: Generate local.properties
                run: echo '${{ secrets.LOCAL_PROPERTIES }}' | base64 -d > ./local.properties

            -   name: Generate keystore.properties
                run: echo '${{ secrets.KEYSTORE_PROPERTIES }}' | base64 -d > ./keystore.properties

            -   name: Generate google-services.json
                run: echo '${{ secrets.GOOGLE_SERVICES }}' | base64 -d > ./app/google-services.json

            -   name: Code style checks
                run: |
                    ./gradlew ktlintCheck detekt

            -   name: Build with Gradle
                run: ./gradlew buildDebug --stacktrace
